### PR TITLE
Fix collaboration cursor bubbles not appearing in coaching notes

### LINKED ISSUE #184: [Bug]: New collaboration bubbles cover over other text
### Contact Details

jim@refactorcoach.com

### What happened?

The new collaboration bubbles that hold the display name of each user in a session are too big. They hide the coaching notes text that is underneath them which can be very frustrating.

Another possible (and maybe preferable) way of fixing this would be to make the bubble go translucent when the mouse cursor hovers over the bubble, revealing the otherwise blocked text beneath it.

### What is the version of refactor-platform-fe that you're seeing the problem on?

1.0.0-rc2

### Any related code or configuration details to produce this issue as well as relevant log output.

```shell

```

### LINKED ISSUE #201: [Bug]: Cursor and collaboration bubble missing from other collaborator during coaching session
### Contact Details

jim@refactorcoach.com

### What happened?

When in a coaching session with a client of mine, I noticed that they were able to type in the coaching notes, but neither they, nor myself, could see each other's cursor nor collaboration bubble.

### What is the version of refactor-platform-fe that you're seeing the problem on?

1.0.0-beta2

### PR DESCRIPTION
**Pull request by jhodapp**
## Description
Fix collaboration cursor bubbles not appearing in coaching session notes. The issue was caused by the React useEffect cleanup function disconnecting the TipTap collaboration provider whenever dependencies changed, even when the session ID remained the same. This resulted in cursors disappearing when users clicked between browsers.

This also seems to fix the instability of the presence indicators at the top of the coaching session page as well. The unstable user presence in each browser (coach and coachee) seem to be directly related to unstable user carets as well.

**Additional fixes**: Further improvements to presence indicator behavior during network disconnects, visual consistency of collaboration carets, and UX enhancements for caret name bubbles.

### Changes

**Core Collaboration Fixes:**
* Fixed useEffect cleanup to only disconnect provider on session change, not on dependency changes
* Prevented provider recreation when re-rendering with the same sessionId
* Added guard to prevent multiple extension creation on repeated synced events
* Switched from low-level `provider.awareness.setLocalStateField()` to high-level `provider.setAwarenessField()` API
* Removed unnecessary mouse position tracking that was interfering with cursor tracking
* Fixed awareness state type from `Map` to `Array` to match Hocuspocus API
* Implemented unique color generation per user session using `generateCollaborativeUserColor()`

**Presence Indicator Fixes:**
* Removed setAwarenessField call from disconnect event handler (message can't be delivered when already offline)
* Preserve users who disappear from awareness states as disconnected instead of removing them
* Merge previous presence state with current awareness data to maintain user tracking
* Ensures network disconnect and browser close produce identical behavior (correct user shows as disconnected)

**Visual Consistency & UX Fixes:**
* Changed collaboration caret height from `1.2em` to `1em` to match actual text height
* Added `line-height: inherit` and `vertical-align: baseline` for consistent caret rendering
* Ensures all carets have uniform heights regardless of document context
* Added hover transparency effect (20% opacity) to caret name bubbles for better content visibility
* Changed `pointer-events` from `none` to `auto` to enable hover interactions
* Added cursor pointer and enhanced shadow on hover for better interactivity feedback

**Test Coverage:**
* Added comprehensive test coverage for provider lifecycle, extension creation, and awareness state management
* Added test for users being marked as disconnected when they disappear from awareness states
* Updated disconnect event test to reflect new behavior (no setAwarenessField call)
* All 11 tests passing

### Screenshots / Videos Showing UI Changes (if applicable)

Screenshot 2025-11-13 at 22 14 30

Screenshot 2025-11-13 at 22 14 42

### Testing Strategy
1. **Unit Tests**: All 11 tests in `editor-cache-context.test.tsx` pass, covering:
   - Provider lifecycle (no disconnect on re-render with same sessionId)
   - Provider cleanup (disconnect on sessionId change)
   - Extension creation (only once despite multiple synced events)
   - Awareness API usage (high-level `setAwarenessField()`)
   - Presence state updates on awarenessChange events
   - Users marked as disconnected when they disappear from awareness states
   - No setAwarenessField call on disconnect event

2. **Manual Testing**:
   - Open the same coaching session in two browser windows
   - Log in as coach in one, coachee in the other
   - Click around and type in the coaching notes editor
   - Verify both users can see each other's cursors continuously
   - Verify cursors don't disappear when clicking between browsers
   - Test network disconnect: Set one browser to offline mode in dev tools
   - Verify the correct user shows as disconnected (grey indicator)
   - Verify caret heights are consistent across all text contexts
   - Hover over caret name bubbles and verify they become transparent (20% opacity)

### Concerns
None. The fix addresses the root cause of the provider disconnection issue and includes comprehensive test coverage to prevent regression.

### CODE REVIEW

File: src/components/ui/coaching-sessions/editor-cache-context.tsx [hunk 1]
```diff
@@ -179,15 +190,41 @@ export const EditorCacheProvider: React.FC<EditorCacheProviderProps> = ({
...
+            for (const [userId, oldPresence] of prev.presenceState.users) {
+              if (!updatedUsers.has(userId) && oldPresence.status === 'connected') {
+                // User was connected but no longer in awareness states - mark as disconnected
+                mergedUsers.set(userId, {
+                  ...oldPresence,
+                  status: 'disconnected',
+                  isConnected: false,
+                  lastSeen: new Date()
+                });
+              }
```
Comment (calebbourg) [inline src/components/ui/coaching-sessions/editor-cache-context.tsx]: I'm curious what this provides? What is the issue if users "Disappear" and what does that mean exactly?
